<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LTPPUN052363123" ignored="0" name="Test - Login functionality - MAC" tests="3" failures="2" timestamp="2020-12-14T17:26:43 IST" time="190.526" errors="0">
  <testcase name="loginTest" time="24.011" classname="test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Itest@test.com] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Itest@test.com] but found [null]
at test.LoginTest.loginTest(LoginTest.java:48)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="10.091" classname="test.LoginTest"/>
  <testcase name="loginTest" time="4.466" classname="test.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Itest@test.com] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Itest@test.com] but found [null]
at test.LoginTest.loginTest(LoginTest.java:48)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Test - Login functionality - MAC -->
